//
//  PrefixParser.swift
//  PrefixPackageDescription
//
//  Created by Borinschi Ivan on 4/23/18.
//

import Foundation

public enum PrefixParserPatternTag {}
public typealias PrefixParserPattern = PrefixTypedValue<PrefixParserPatternTag, String>

public let swiftTypeDeclarationsPosibleEnds = [" ", ":", "{", "?", ",", ".", "<","(",")","]","\n", ">"]
public let swiftTypeDeclarationsPosibleBegins = [" ", "[", "(", ":", ".","<", "&",">"]
public let swiftTypes = ["class", "protocol", "extension", "enum", "struct"]
public var swiftPrivateTypes: [String] {
    
    var privateTypes = ["Int",
                        "Double",
                        "Decimal",
                        "NumberFormatter",
                        "Data",
                        "URL",
                        "URLComponents",
                        "URLQueryItem",
                        "UUID",
                        "CGFloat",
                        "NSPoint",
                        "NSSize",
                        "NSRect",
                        "AffineTransform",
                        "NSEdgeInsets",
                        "NSRange",
                        "String",
                        "NSAttributedString",
                        "NSMutableAttributedString",
                        "CharacterSet",
                        "UnicodeScalar",
                        "NSLinguisticTagger",
                        "Scanner",
                        "NSRegularExpression",
                        "NSDataDetector",
                        "NSTextCheckingResult",
                        "NSNotFound",
                        "NSSpellServer",
                        "NSSpellServerDelegate",
                        "Locale",
                        "NSOrthography",
                        "Array",
                        "Dictionary",
                        "Set",
                        "IndexPath",
                        "IndexSet",
                        "NSCountedSet",
                        "NSOrderedSet",
                        "NSMutableOrderedSet",
                        "NSCache",
                        "NSPurgeableData",
                        "NSPointerArray",
                        "NSMapTable",
                        "NSHashTable",
                        "NSEnumerator",
                        "NSFastEnumeration",
                        "NSFastEnumerationIterator",
                        "NSIndexSetIterator",
                        "NSEnumerationOptions",
                        "NSSortOptions",
                        "NSNull",
                        "NSNotFound",
                        "Date",
                        "DateInterval",
                        "TimeInterval",
                        "DateComponents",
                        "DateFormatter",
                        "DateComponentsFormatter",
                        "DateIntervalFormatter",
                        "ISO8601DateFormatter",
                        "Locale",
                        "Measurement",
                        "Unit",
                        "Dimension",
                        "UnitConverter",
                        "UnitConverterLinear",
                        "UnitArea",
                        "UnitLength",
                        "UnitVolume",
                        "UnitAngle",
                        "UnitMass",
                        "UnitPressure",
                        "UnitAcceleration",
                        "UnitDuration",
                        "UnitFrequency",
                        "UnitSpeed",
                        "UnitPower",
                        "UnitTemperature",
                        "UnitIlluminance",
                        "UnitElectricCharge",
                        "UnitElectricCurrent",
                        "UnitElectricPotentialDifference",
                        "UnitElectricResistance",
                        "UnitConcentrationMass",
                        "UnitDispersion",
                        "UnitFuelEfficiency",
                        "PersonNameComponentsFormatter",
                        "PersonNameComponents",
                        "DateFormatter",
                        "DateComponentsFormatter",
                        "DateIntervalFormatter",
                        "ISO8601DateFormatter",
                        "ByteCountFormatter",
                        "MeasurementFormatter",
                        "Formatter",
                        "LengthFormatter",
                        "MassFormatter",
                        "EnergyFormatter",
                        "NSPredicate",
                        "NSExpression",
                        "NSComparisonPredicate",
                        "NSCompoundPredicate",
                        "NSSortDescriptor",
                        "ComparisonResult",
                        "DispatchQueue"]
    
    privateTypes.append(contentsOf: uikitPrivateTypes)
    privateTypes.append(contentsOf: foundationPrivateTypes)
    privateTypes.append(contentsOf: swiftFoundationPrivateTypes)
    
    return privateTypes
}

public let uikitPrivateTypes = ["DocumentManager",
                                "NSAttributedString",
                                "NSDataAsset",
                                "NSFileProviderExtension",
                                "NSIndexPath_UIKitAdditions",
                                "NSItemProvider_UIKitAdditions",
                                "NSLayoutAnchor",
                                "NSLayoutConstraint",
                                "NSLayoutManager",
                                "NSParagraphStyle",
                                "NSShadow",
                                "NSStringDrawing",
                                "NSText",
                                "NSTextAttachment",
                                "NSTextContainer",
                                "NSTextStorage",
                                "UIAccelerometer",
                                "UIAccessibility",
                                "UIAccessibilityAdditions",
                                "UIAccessibilityConstants",
                                "UIAccessibilityContainer",
                                "UIAccessibilityContentSizeCategoryImageAdjusting",
                                "UIAccessibilityCustomAction",
                                "UIAccessibilityCustomRotor",
                                "UIAccessibilityElement",
                                "UIAccessibilityIdentification",
                                "UIAccessibilityLocationDescriptor",
                                "UIAccessibilityZoom",
                                "UIActionSheet",
                                "UIActivity",
                                "UIActivityIndicatorView",
                                "UIActivityItemProvider",
                                "UIActivityViewController",
                                "UIAlert",
                                "UIAlertController",
                                "UIAlertView",
                                "UIAppearance",
                                "UIApplication",
                                "UIApplicationShortcutItem",
                                "UIAttachmentBehavior",
                                "UIBarButtonItem",
                                "UIBarButtonItemGroup",
                                "UIBarCommon",
                                "UIBarItem",
                                "UIBezierPath",
                                "UIBlurEffect",
                                "UIButton",
                                "UICloudSharingController",
                                "UICollectionView",
                                "UICollectionViewCell",
                                "UICollectionViewController",
                                "UICollectionViewFlowLayout",
                                "UICollectionViewLayout",
                                "UICollectionViewTransitionLayout",
                                "UICollisionBehavior",
                                "UIColor",
                                "UIContentSizeCategory",
                                "UIContentSizeCategoryAdjusting",
                                "UIContextualAction",
                                "UIControl",
                                "UIDataDetectors",
                                "UIDataSourceTranslating",
                                "UIDatePicker",
                                "UIDevice",
                                "UIDocument",
                                "UIDocumentInteractionController",
                                "UIDocumentMenuViewController",
                                "UIDocumentPickerExtensionViewController",
                                "UIDocumentPickerViewController",
                                "UIDragInteraction",
                                "UIDragItem",
                                "UIDragPreview",
                                "UIDragPreviewParameters",
                                "UIDragSession",
                                "UIDropInteraction",
                                "UIDynamicAnimator",
                                "UIDynamicBehavior",
                                "UIDynamicItemBehavior",
                                "UIEvent",
                                "UIFeedbackGenerator",
                                "UIFieldBehavior",
                                "UIFocus",
                                "UIFocusAnimationCoordinator",
                                "UIFocusDebugger",
                                "UIFocusGuide",
                                "UIFocusSystem",
                                "UIFont",
                                "UIFontDescriptor",
                                "UIFontMetrics",
                                "UIGeometry",
                                "UIGestureRecognizer",
                                "UIGestureRecognizerSubclass",
                                "UIGraphics",
                                "UIGraphicsImageRenderer",
                                "UIGraphicsPDFRenderer",
                                "UIGraphicsRenderer",
                                "UIGraphicsRendererSubclass",
                                "UIGravityBehavior",
                                "UIGuidedAccessRestrictions",
                                "UIImage",
                                "UIImageAsset",
                                "UIImagePickerController",
                                "UIImageView",
                                "UIImpactFeedbackGenerator",
                                "UIInputView",
                                "UIInputViewController",
                                "UIInteraction",
                                "UIInterface",
                                "UIKitDefines",
                                "UILabel",
                                "UILayoutGuide",
                                "UILexicon",
                                "UILocalNotification",
                                "UILocalizedIndexedCollation",
                                "UILongPressGestureRecognizer",
                                "UIManagedDocument",
                                "UIMenuController",
                                "UIMotionEffect",
                                "UINavigationBar",
                                "UINavigationController",
                                "UINavigationItem",
                                "UINib",
                                "UINibDeclarations",
                                "UINibLoading",
                                "UINotificationFeedbackGenerator",
                                "UIPageControl",
                                "UIPageViewController",
                                "UIPanGestureRecognizer",
                                "UIPasteConfiguration",
                                "UIPasteConfigurationSupporting",
                                "UIPasteboard",
                                "UIPickerView",
                                "UIPinchGestureRecognizer",
                                "UIPopoverBackgroundView",
                                "UIPopoverController",
                                "UIPopoverPresentationController",
                                "UIPopoverSupport",
                                "UIPresentationController",
                                "UIPress",
                                "UIPressesEvent",
                                "UIPreviewInteraction",
                                "UIPrintError",
                                "UIPrintFormatter",
                                "UIPrintInfo",
                                "UIPrintInteractionController",
                                "UIPrintPageRenderer",
                                "UIPrintPaper",
                                "UIPrinter",
                                "UIPrinterPickerController",
                                "UIProgressView",
                                "UIPushBehavior",
                                "UIReferenceLibraryViewController",
                                "UIRefreshControl",
                                "UIRegion",
                                "UIResponder",
                                "UIRotationGestureRecognizer",
                                "UIScreen",
                                "UIScreenEdgePanGestureRecognizer",
                                "UIScreenMode",
                                "UIScrollView",
                                "UISearchBar",
                                "UISearchContainerViewController",
                                "UISearchController",
                                "UISearchDisplayController",
                                "UISegmentedControl",
                                "UISelectionFeedbackGenerator",
                                "UISlider",
                                "UISnapBehavior",
                                "UISplitViewController",
                                "UISpringLoadedInteraction",
                                "UISpringLoadedInteractionSupporting",
                                "UIStackView",
                                "UIStateRestoration",
                                "UIStepper",
                                "UIStoryboard",
                                "UIStoryboardPopoverSegue",
                                "UIStoryboardSegue",
                                "UIStringDrawing",
                                "UISwipeActionsConfiguration",
                                "UISwipeGestureRecognizer",
                                "UISwitch",
                                "UITabBar",
                                "UITabBarController",
                                "UITabBarItem",
                                "UITableView",
                                "UITableViewCell",
                                "UITableViewController",
                                "UITableViewHeaderFooterView",
                                "UITapGestureRecognizer",
                                "UITargetedDragPreview",
                                "UITextChecker",
                                "UITextDragPreviewRenderer",
                                "UITextDragURLPreviews",
                                "UITextDragging",
                                "UITextDropProposal",
                                "UITextDropping",
                                "UITextField",
                                "UITextInput",
                                "UITextInputTraits",
                                "UITextInteraction",
                                "UITextPasteConfigurationSupporting",
                                "UITextPasteDelegate",
                                "UITextView",
                                "UITimingCurveProvider",
                                "UITimingParameters",
                                "UIToolbar",
                                "UITouch",
                                "UITraitCollection",
                                "UIUserNotificationSettings",
                                "UIVibrancyEffect",
                                "UIVideoEditorController",
                                "UIView",
                                "UIViewAnimating",
                                "UIViewController",
                                "UIViewControllerTransitionCoordinator",
                                "UIViewControllerTransitioning",
                                "UIViewPropertyAnimator",
                                "UIVisualEffect",
                                "UIVisualEffectView",
                                "UIWebView",
                                "UIWindow"]

public var foundationPrivateTypes = ["CoreFoundation",
                                     "CoreGraphics",
                                     "Darwin.uuid",
                                     "Darwin",
                                     "FoundationErrors",
                                     "FoundationLegacySwiftCompatibility",
                                     "NSArray",
                                     "NSAttributedString",
                                     "NSAutoreleasePool",
                                     "NSBundle",
                                     "NSByteCountFormatter",
                                     "NSByteOrder",
                                     "NSCache",
                                     "NSCalendar",
                                     "NSCharacterSet",
                                     "NSCoder",
                                     "NSComparisonPredicate",
                                     "NSCompoundPredicate",
                                     "NSData",
                                     "NSDate",
                                     "NSDateComponentsFormatter",
                                     "NSDateFormatter",
                                     "NSDateInterval",
                                     "NSDateIntervalFormatter",
                                     "NSDecimal",
                                     "NSDecimalNumber",
                                     "NSDictionary",
                                     "NSEnergyFormatter",
                                     "NSEnumerator",
                                     "NSError",
                                     "NSException",
                                     "NSExpression",
                                     "NSExtensionContext",
                                     "NSExtensionItem",
                                     "NSExtensionRequestHandling",
                                     "NSFileCoordinator",
                                     "NSFileHandle",
                                     "NSFileManager",
                                     "NSFilePresenter",
                                     "NSFileVersion",
                                     "NSFileWrapper",
                                     "NSFormatter",
                                     "NSHTTPCookie",
                                     "NSHTTPCookieStorage",
                                     "NSHashTable",
                                     "NSISO8601DateFormatter",
                                     "NSIndexPath",
                                     "NSIndexSet",
                                     "NSInvocation",
                                     "NSItemProvider",
                                     "NSJSONSerialization",
                                     "NSKeyValueCoding",
                                     "NSKeyValueObserving",
                                     "NSKeyedArchiver",
                                     "NSLengthFormatter",
                                     "NSLinguisticTagger",
                                     "NSLocale",
                                     "NSLock",
                                     "NSMapTable",
                                     "NSMassFormatter",
                                     "NSMeasurement",
                                     "NSMeasurementFormatter",
                                     "NSMetadata",
                                     "NSMetadataAttributes",
                                     "NSMethodSignature",
                                     "NSNetServices",
                                     "NSNotification",
                                     "NSNotificationQueue",
                                     "NSNull",
                                     "NSNumberFormatter",
                                     "NSNumber",
                                     "NSObjCRuntime",
                                     "NSObject",
                                     "NSOperation",
                                     "NSOrderedSet",
                                     "NSOrthography",
                                     "NSPathUtilities",
                                     "NSPersonNameComponents",
                                     "NSPersonNameComponentsFormatter",
                                     "NSPointerArray",
                                     "NSPointerFunctions",
                                     "NSPort",
                                     "NSPredicate",
                                     "NSProcessInfo",
                                     "NSProgress",
                                     "NSPropertyList",
                                     "NSProxy",
                                     "NSRange",
                                     "NSRegularExpression",
                                     "NSRunLoop",
                                     "NSScanner",
                                     "NSSet",
                                     "NSSortDescriptor",
                                     "NSStream",
                                     "NSString",
                                     "NSTextCheckingResult",
                                     "NSThread",
                                     "NSTimeZone",
                                     "NSTimer",
                                     "NSURL",
                                     "NSURLAuthenticationChallenge",
                                     "NSURLCache",
                                     "NSURLConnection",
                                     "NSURLCredential",
                                     "NSURLCredentialStorage",
                                     "NSURLError",
                                     "NSURLProtectionSpace",
                                     "NSURLProtocol",
                                     "NSURLRequest",
                                     "NSURLResponse",
                                     "NSURLSession",
                                     "NSUUID",
                                     "NSUbiquitousKeyValueStore",
                                     "NSUndoManager",
                                     "NSUnit",
                                     "NSUserActivity",
                                     "NSUserDefaults",
                                     "NSValue",
                                     "NSValueTransformer",
                                     "NSXMLParser",
                                     "NSXPCConnection",
                                     "NSZone",]

public var swiftFoundationPrivateTypes = ["AttributedString",
                                     "AutoreleasePool",
                                     "Bundle",
                                     "ByteCountFormatter",
                                     "ByteOrder",
                                     "Cache",
                                     "Calendar",
                                     "CharacterSet",
                                     "Coder",
                                     "ComparisonPredicate",
                                     "CompoundPredicate",
                                     "Data",
                                     "Date",
                                     "DateComponentsFormatter",
                                     "DateFormatter",
                                     "DateInterval",
                                     "DateIntervalFormatter",
                                     "Decimal",
                                     "DecimalNumber",
                                     "Dictionary",
                                     "EnergyFormatter",
                                     "Enumerator",
                                     "Error",
                                     "Exception",
                                     "Expression",
                                     "ExteionContext",
                                     "ExteionItem",
                                     "ExteionRequestHandling",
                                     "FileCoordinator",
                                     "FileHandle",
                                     "FileManager",
                                     "FilePresenter",
                                     "FileVersion",
                                     "FileWrapper",
                                     "Formatter",
                                     "HTTPCookie",
                                     "HTTPCookieStorage",
                                     "HashTable",
                                     "ISO8601DateFormatter",
                                     "IndexPath",
                                     "IndexSet",
                                     "Invocation",
                                     "ItemProvider",
                                     "JSOerialization",
                                     "KeyValueCoding",
                                     "KeyValueObserving",
                                     "KeyedArchiver",
                                     "LengthFormatter",
                                     "LinguisticTagger",
                                     "Locale",
                                     "Lock",
                                     "MapTable",
                                     "MassFormatter",
                                     "Measurement",
                                     "MeasurementFormatter",
                                     "Metadata",
                                     "MetadataAttributes",
                                     "MethodSignature",
                                     "NetServices",
                                     "Notification",
                                     "NotificationQueue",
                                     "Null",
                                     "NumberFormatter",
                                     "ObjCRuntime",
                                     "Object",
                                     "Operation",
                                     "OrderedSet",
                                     "Orthography",
                                     "PathUtilities",
                                     "PersonNameComponents",
                                     "PersonNameComponentsFormatter",
                                     "PointerArray",
                                     "PointerFunctio",
                                     "Port",
                                     "Predicate",
                                     "ProcessInfo",
                                     "Progress",
                                     "PropertyList",
                                     "Proxy",
                                     "Range",
                                     "RegularExpression",
                                     "RunLoop",
                                     "Scanner",
                                     "Set",
                                     "SortDescriptor",
                                     "Stream",
                                     "String",
                                     "TextCheckingResult",
                                     "Thread",
                                     "TimeZone",
                                     "Timer",
                                     "URL",
                                     "URLAuthenticationChallenge",
                                     "URLCache",
                                     "URLConnection",
                                     "URLCredential",
                                     "URLCredentialStorage",
                                     "URLError",
                                     "URLProtectiopace",
                                     "URLProtocol",
                                     "URLRequest",
                                     "URLRespoe",
                                     "URLSession",
                                     "UUID",
                                     "UbiquitousKeyValueStore",
                                     "UndoManager",
                                     "Unit",
                                     "UserActivity",
                                     "UserDefaults",
                                     "Value",
                                     "ValueTraformer",
                                     "XMLParser",
                                     "XPCConnection",
                                     "Zone",]


public class PrefixParser {
    
    private static var cachedRegularExpressions: [String: NSRegularExpression] = [:]
    
    /// Create PrefixParserPattern which will check if string contain word
    ///
    /// - Parameter word: Word to be contained
    /// - Returns: PrefixParserPattern
    public static func containWord(_ word: String) -> PrefixParserPattern {
        return PrefixParserPattern("(?:\\\(word))")
    }
    
    /// Create contain Swift Type Declaration
    ///
    /// - Parameter type: String
    /// - Returns: PrefixParserPattern
    public static func containSwiftTypeDeclarations(_ type: String) -> [PrefixParserPattern] {
        
        var patterns = [PrefixParserPattern]()
        for end in swiftTypeDeclarationsPosibleEnds {
            patterns.append(PrefixParserPattern("(?:\(type))(?:\\ )\\w+(?:\\\(end))"))
        }
        
        return patterns
    }
    
    /// Get elements from string
    ///
    /// - Parameters:
    ///   - text: String
    ///   - pattern: PrefixParserPattern
    ///   - range: NSRange
    /// - Returns: [NSTextCheckingResult]
    public static func getElements(from text: String,
                            with pattern: PrefixParserPattern,
                            range: NSRange) -> [NSTextCheckingResult] {
        
        guard let elementRegex = regularExpression(for: pattern) else { return [] }
        return elementRegex.matches(in: text, options: [], range: range)
    }
    
    /// Make an regular expresion
    ///
    /// - Parameter pattern: PrefixParserPattern
    /// - Returns: NSRegularExpression?
    public static func regularExpression(for pattern: PrefixParserPattern) -> NSRegularExpression? {
        
        if let regex = cachedRegularExpressions[pattern.value] {
            return regex
        } else if let createdRegex = try? NSRegularExpression(pattern: pattern.value, options: [.caseInsensitive]) {
            cachedRegularExpressions[pattern.value] = createdRegex
            return createdRegex
        } else {
            return nil
        }
    }
}
